name:                           Build and Test Suite

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - beta
jobs:
  build-tests:
    name:                       Test and Build
    strategy:
      matrix:
        platform:
          - ubuntu-22.04
        #  - macos-latest
        toolchain:
          -  1.85
    runs-on:                    ${{ matrix.platform }}
    steps:
      - name:                   Checkout sources
        uses:                   actions/checkout@main
        with:
          submodules:           true
      - name:                   Install toolchain
        uses:                   actions-rs/toolchain@v1
        with:
          toolchain:            ${{ matrix.toolchain }}
          profile:              minimal
          override:             true
      - name:                   Build tests
        uses:                   actions-rs/cargo@v1
        with:
          command:              test
          #args: deactivated JSON Tests, so we do not run out of quota on CI tests for merge intesive time.  --locked --all --release --features "json-tests" --verbose --no-run
          args:                 --locked --all --release --verbose --no-run
      - name:                   Run tests for ${{ matrix.platform }}
        uses:                   actions-rs/cargo@v1
        with:
          command:              test
          #args: deactivated JSON Tests                --locked --all --release --features "json-tests" --verbose
          args:                 --locked --all --release --verbose

